spring:
  application:
    name: invoice
  datasource:
    url: jdbc:postgresql://localhost:5432/invoice
    username: postgres
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

basic:
  auth:
    username: user
    password: password